#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod a_file;
pub mod console;
pub mod console_2;
pub mod counter;
pub mod erc20;
pub mod i_uniswap_v2_callee;
pub mod i_uniswap_v2_factory;
pub mod i_uniswap_v2_pair;
pub mod i_uniswap_v2erc20;
pub mod ierc20;
pub mod math;
pub mod safe_math;
pub mod std_error;
pub mod std_json;
pub mod std_math;
pub mod std_storage;
pub mod uniswap_v2_factory;
pub mod uniswap_v2_pair;
pub mod uniswap_v2erc20;
pub mod uq11_2x_112;
pub mod vm;
